# General config
root        :
weights     :
model       :
data        :
fullname    :
save_dir    :
device      :
epochs      :
steps       :
imgsz       :
resize      :
benchmark   :
save_image  :
use_data_dir:
exist_ok    :
verbose     :

# Model

# Training
